### ISSUE TITLE
Support newest Fabric API Version

### ISSUE THREAD

**Issue by OfficialCRUGG** [TheMysterys/MCCI-Utils#26]
The newest Fabric API Version (0.69.0+1.19.3) is not supported at the moment. It would be great to support this for more user-friendliness and cross-compatibility between mods.

Besides that, couldn't you just allow for all versions above the required one by prefixing the version with `>`?

**Comment by TheMysterys** [comment]
Whoops that's a mistake on my end. Forgot when setting the required fabric api version to make it accept future versions. I'll post a hot fix asap

**Comment by TheMysterys** [comment]
Just pushed an update 0.15.1. Should hopefully fix this problem
