### ISSUE TITLE
Friend Notification Toast Isn't Showing

### ISSUE THREAD

**Issue by Flameri** [TheMysterys/MCCI-Utils#6]
Basically what the title says, I have them enabled in the config menu but they still don't show up. The sound works though.
The mod is at the top of my mods folder, so it loads before all other mods.
I also have 3 pages of friends if this would make a difference.
**My Mods List:**
Better Controls
BetterF3
Bobby
Boosted Brightness
Camera Utils
Capes
Chat Up!
Collective
Fabric Language Kotlin
FerriteCore
fiber
FPS Reducer
GUI Clock
Inventory HUD+
Islandutils
LazyDFU
Lithium
MaLiLib
MCCI Utils
MiniHUD
Mod Menu
No Fog
Replay Mod
Sodium
WI Zoom
![image](https://user-images.githubusercontent.com/112080561/190899157-030f552d-165d-4841-a1aa-0510054d44eb.png)
![image](https://user-images.githubusercontent.com/112080561/190899175-0f494375-2f25-4475-ad6f-4d1e961e77b9.png)
![image](https://user-images.githubusercontent.com/112080561/190899183-c6e1a6cb-5ae3-42b8-af6b-7ac572394ad8.png)

**Comment by TheMysterys** [comment]
I'm unable to reproduce this. Could you provide more information, like where you were on the server and stuff

![image](https://user-images.githubusercontent.com/42754166/191008256-4c765100-6d6d-4082-a66d-99e3e3ea6cc0.png)

**Comment by TheMysterys** [comment]
@Flameri please respond in the next few days or I will mark this as invalid since I have not been able to reproduce this bug
